apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: config-example
  labels:
    alertmanagerConfig: example
spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'webhook'
    routes:
    - continue: false
      matchers:
        - alertname =~ "AlertaExemplo123"
    - continue: true
      matchers:
        - namespace =~ "namespace123|namesp.*|.*space"
  receivers:
  - name: 'webhook'
    webhookConfigs:
    - url: 'http://example.com/'
