{
 "title": "Crawlers",
 "tags": [
  "paris",
  "rabbitmq",
  "crawler",
  "log"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "ns",
    "label": "Crawler",
    "query": "crawler-grow, crawler-vw, crawler-myhonda, crawler-renault"
   },
   {
    "name": "app",
    "label": "Serviço",
    "query": "label_values({namespace=\"$ns\"}, app)"
   },
   {
    "name": "queue",
    "query": {
     "query": "label_values(rabbitmq_detailed_queue_messages{vhost=\"$ns\"}, queue)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Headline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU used (from requests)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$ns\", container=~\"$app\"}) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$ns\", container=~\"$app\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "CPU used (from limits)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{container=~\"$app\", namespace=\"$ns\"}) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", container=~\"$app\", namespace=\"$ns\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (queue) (rabbitmq_detailed_queue_consumers{vhost=~\"$ns\"})",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (container) (container_memory_swap{namespace=\"$ns\", container=~\"$app\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory used (from requests)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container=~\"$app\", namespace=\"$ns\", image!=\"\"}) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$ns\", container=~\"$app\", resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Memory used (from limits)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container=~\"$app\", namespace=\"$ns\",container!=\"\", image!=\"\"}) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", container=~\"$app\", namespace=\"$ns\", resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (queue) (rabbitmq_detailed_queue_messages{vhost=~\"$ns\"})",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$ns\", container=~\"$app\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage (w/o cache)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$ns\", container=~\"$app\", image!=\"\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "+Receive -Transmit Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"$ns\", pod=~\"$app.*\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}} received"
      },
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"$ns\", pod=~\"$app.*\"}[$__rate_interval])) by (pod) * -1",
       "legendFormat": "{{pod}} transmited"
      }
     ]
    }
   ]
  },
  {
   "title": "Rabbitmq",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queues",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum by (queue) (rabbitmq_detailed_queue_messages{vhost=~\"$ns\"})",
       "legendFormat": "{{queue}}"
      },
      {
       "expr": "sum by (queue) (rabbitmq_detailed_queue_consumers{vhost=~\"$ns\"})",
       "legendFormat": "{{queue}}"
      },
      {
       "expr": "sum by (queue) (rabbitmq_detailed_queue_messages_ready{vhost=~\"$ns\"})",
       "legendFormat": "{{queue}}"
      },
      {
       "expr": "sum by (queue) (rabbitmq_detailed_queue_messages_unacked{vhost=~\"$ns\"})",
       "legendFormat": "{{queue}}"
      },
      {
       "expr": "sum by (queue) (rabbitmq_detailed_queue_consumer_utilisation{vhost=~\"$ns\"})"
      }
     ]
    },
    {
     "title": "Queues",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum by (queue) (rabbitmq_detailed_queue_messages{vhost=~\"$ns\"})",
       "legendFormat": "{{queue}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log",
     "type": "logs",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "{namespace=\"$ns\", app=~\"$app\"}"
      }
     ]
    }
   ]
  }
 ]
}