apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 

- ../base
- dashboards-via-kustomize/
- alertmanagers/
- elastic+kibana+filebeat.yaml

patches:
- path: monitoring.yaml
- path: prometheus-msteams.yaml
