apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    name: ''
    namespace: elastic-system
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://helm.elastic.co'
    targetRevision: 2.14.0
    chart: eck-operator
    helm: {}
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
 
