apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-msteams
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    name: ''
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://prometheus-msteams.github.io/prometheus-msteams/
    targetRevision: 1.3.4
    chart: prometheus-msteams
    helm:
      values: |-
        resources: 
          limits:
            cpu: 50m
            memory: 64Mi
          requests:
            cpu: 50m
            memory: 64Mi
        
        connectors: 
        - teams: https://365.webhook.office.com/webhookb2/7ca7a253-b66680@6c0c3831-78a8849/IncomingWebhook/e4e0bdc82f/4f6-8346-215db65c9ec
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

